"""Add Review Model

Revision ID: 1caf7a6c4455
Revises: 81df9489168f
Create Date: 2023-08-16 14:27:58.002209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caf7a6c4455'
down_revision = '81df9489168f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
